baseURL: http://www.jessekrijthe.com
disablePathToLower: true
languageCode: en-us
title: Jesse Krijthe
buildDrafts: false
theme: "theme-jk"
author:
  name: Jesse Krijthe
  email: jkrijthe@gmail.com
permalinks:
  articles: /articles/:filename
